version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  redis:  redis:7-alphine   
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
      - redis
    entrypoint: 
      [
        "/app/wait-for.sh", 
        "postgres:5432",
        "--",
        "/app/start.sh"
        ]
    command: ["/app/main"]
